### ISSUE TITLE
Colors not chosen appropriately

### ISSUE THREAD

**Issue by steelbrain** [nathanbuchar/atom-one-dark-terminal#5]
This hurts my eyes
<img src="https://cloud.githubusercontent.com/assets/4278113/15548726/8eae3a34-225e-11e6-939d-81e0eb177a67.png">

The text color shouldn't be so dull, it should be a little brighter

Another place this could be improved is parameters
<img src="https://cloud.githubusercontent.com/assets/4278113/15548767/b228a490-225e-11e6-8613-d90914f53494.png">

**Comment by nathanbuchar** [comment]
Hey, thanks for trying it out!

This is of course personal preference – although I will admit that on many projects in the past I have been told that my choice of font colors are too light or dull and lacking in contrast. Personally I have never found an issue with them, but certainly from an accessibility prospective it could use more contrast. The contrast is also dependent on your monitor; I've seen text that shows up as clear as day on one screen look almost invisible on another.

This shade of gray was chosen because it's the same shade of gray used for line comments in the One Dark theme. I was constrained to using colors only found in the One Dark palette, and I felt that using white was much too bright and I was already using a slightly brighter shade for bolded text.

With thousands of downloads, this is the only issue with regarding text contrast so far so I think I'll keep it as is for now. However I'll keep the issue open, and if it gets a bit more support I have no issue boosting the contrast :)

In the meantime, it's always very easy to modify this yourself. Simply open up your Terminal preferences, select the One Dark profile, and change the color for "Text".

**Comment by nixpulvis** [comment]
This is the first and only part of this theme I change. The reason for this is that while comments sit at a level apart from my source code, and therefor deserve a more subdued color, plain text in a terminal is the primary tenant and should be more pronounced.

**Comment by nathanbuchar** [comment]
Thanks for the feedback. What color do you change it to, or what would you suggest that I change it to?

**Comment by nixpulvis** [comment]
I'm currently using `#abb2bf` which was taken from the text color of one-dark.

**Comment by thomasboyt** [comment]
Thanks for mentioning the hex code @nixpulvis; I installed this theme and had the same immediate reaction. I'm various curious what screens people are using where this is enough contrast for them; on both my Macbook Air and my UltraSharp monitor this was waaaay too low of contrast.

According to http://webaim.org/resources/contrastchecker/, the default foreground-on-background has a contrast ratio of 3.09:1, significantly under the recommended 4.5:1. I understand your desire for subdued text, but I think a contrast ratio so low really shouldn't ship as the default - maybe a "muted" option would be more appropriate?

(Other than this nitpick I quite like this theme, thanks @nathanbuchar 😄 )

**Comment by nathanbuchar** [comment]
Alright, I'm convinced. If someone would like to submit a PR, I will accept it

**Comment by thomasboyt** [comment]
Hi @nathanbuchar - it looks like your change in https://github.com/nathanbuchar/atom-one-dark-terminal/commit/dbd53f195d7fd7798bfd194335c3460b7d8b914e may have accidentally reverted the change in https://github.com/nathanbuchar/atom-one-dark-terminal/pull/7. Was that intentional?
